name: telegram_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^2.0.0-beta.2
#  socket_io_client: ^1.0.2
  get: ^4.6.1
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
