name: telegram_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^2.0.0-beta.2
#  socket_io_client: ^1.0.2
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  #state managers
  get: ^4.6.1
  flutter_bloc: ^8.0.1
  sealed_flutter_bloc: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
