name: Deploy

on:
  push:
    branches:
      - feat/github-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build flutter web
        run: |
          flutter pub get
          flutter build web
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKUDEPLOYER }}
          HEROKU_EMAIL: "hosseinkhojany1380@gmail.com"
      
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: "flutterchatting"
      - name: Pull git
        run: git pull
      - name: Push to Heroku
        run: git push heroku master

      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: "markdown"
          message: |
            *New Version of Messenger deployed to Heroku!*
            [View the app](https://flutterchatting.herokuapp.com/)
